

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "johnm",
    "password": "password"
}

###

GET http://localhost:3000/logout
Content-Type: application/json


###
GET http://api.marketstack.com/v1/tickers?search=SMT&access_key=6658f5c2f61c27c847e0aa612d7ff3ea&limit=5


###
GET https://api.marketstack.com/v1/eod/latest?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=SMT.FTSE,DGE.FTSE&limit=5


###
GET https://api.marketstack.com/v1/intraday/latest?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=SMT,DGE&exchange=FTSE&limit=5


###
GET https://api.marketstack.com/v1/intraday/latest?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=SMT.XLON

###
GET https://api.marketstack.com/v1/intraday/latest?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=SBUX,CRM,


###

GET https://api.marketstack.com/v1/eod?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&exchange=FTSE&symbols=SMT,DGE,PRU
# GET https://api.marketstack.com/v1/exchanges/XNAS/intraday/latest?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=MSFT,AAPL

###
POST http://localhost:3000/api/share
content-type: application/json
Authorization: accessToken eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ZDRmNTkxLTQ2ZmQtNDg1Zi05ZWMzLWRlNzgyM2I5M2NhNiIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ik1vcmdhbiIsInVzZXJuYW1lIjoiam9obm0iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTM5MDY1MTMsImV4cCI6MTY5MzkwNjUyM30.0gEZSGwOSbb-csQxM6ll1AyIfPJjFvcJf5vWNzAK8x0

{
        "symbol": "ABC",
        "share_name": "Fake company",
        "exchange_acronym": "XLON",
        "exchange_name": "London Stock Exchange",
        "exchange_country": "UK",
        "exchange_city": "London",
        "bookCost": 20,
        "quantity": 1,
        "userId": "b8d4f591-46fd-485f-9ec3-de7823b93ca6"                                 
}

###

GET https://api.marketstack.com/v1/eod?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=DJI.INDX

###
GET https://api.marketstack.com/v1/eod?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=IXIC.INDX&limit=5

###

GET https://api.marketstack.com/v1/eod?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=FTSE.INDX&limit=5

###


GET https://api.marketstack.com/v1/eod?access_key=6658f5c2f61c27c847e0aa612d7ff3ea&symbols=FTSE250.INDX&limit=1

###

GET https://api.marketstack.com/v1/exchanges/DJI?access_key=6658f5c2f61c27c847e0aa612d7ff3ea

###

GET https://api.marketstack.com/v1/eod?access_key={myKey}&symbols=XNAS.INDX&limit=1
GET https://api.marketstack.com/v1/eod?access_key={myKey}&symbols=XLON.INDX&limit=1




GET https://api.marketstack.com/v1/eod?access_key={myKey}&symbols=DJI.INDX&limit=1

GET https://api.marketstack.com/v1/eod?access_key={myKey}&symbols=XNAS.INDX&limit=1

GET https://api.marketstack.com/v1/eod?access_key={myKey}&symbols=XLON.INDX&limit=1

###

GET https://v6.exchangerate-api.com/v6/50bf31e492548feacfdaa0ab/latest/USD
###